### ISSUE TITLE
feature request: support afl-fuzz -f option

### ISSUE THREAD

**Issue by kcwu** [bnagy/crashwalk#2]

**Comment by bnagy** [comment]
I'm not sure what you would want this option to do. The actual crashfile on disk is the file that is used - how would the argument to -f be used? Copy the crashfile to that filename? And.. why?

As an aside, it's a little uncool to provide NO issue description at all.

**Comment by kcwu** [comment]
Sorry for unclear request.

afl-fuzz -f is useful in two cases.
1. the target program need the input filename ending with certain extension, like .jpg
2. the target program has no way to specify input file. Instead, it read file from hard coded path.

It would be nice crashwalk can support it too.

**Comment by bnagy** [comment]
OK.. So effectively you'd want the crashfile copied to the -f argument. This is going to be racy with >1 worker for case 2. For 1 you could specify just an extension, I guess, and just use per-worker tempfiles. I'll take a look next week.

**Comment by bnagy** [comment]
I'm not going to implement this for the time being, because I can't think of a way to do it that's not kludgy as hell. At best, I might implement a template filename, similar to afl-launch, at least that can be done without being racy.

**Comment by bnagy** [comment]
OK, limited version of this implemented in 34289b82285533f51cd2dbbb71f0caf26800b62e, see README.md for details.
