### ISSUE TITLE
cwtriage doesn't play nicely when binaries implicitly read from stdin

### ISSUE THREAD

**Issue by yrp604** [bnagy/crashwalk#4]
I generally set my binaries up to read from stdin by default. This works fine with afl, however:

```
$ cwtriage -afl -root xxx-output/
2015/08/11 11:23:32 internal error: Job command too short: {xxx-output/xxx-slave-1/crashes/id:000000 0xc20801a960 [./xxx-fuzz]}
```

Even if you work around this with somethng like:

```
$ cwtriage -match crashes.\*id -root xxx-output/ -- ./xxx-fuzz \< @@
```

you get errors:

```
Command: ./xxx-fuzz < xxx-output/xxx-slave-5/crashes/id:000000
File: xxx-output/xxx-slave-1/crashes/id:000000
Error: no gdb output
```

I think you could do this with something like 'gdb -ex "set args < testcase"' or by modifying the gdb commands ('run' -> 'run < testcase'). I looked over it for a bit, and don't see any clean way to start gdb where it will Just Work. This means the interface between crashwalk.go and gdb.go would have to include if it's expecting the testcase via stdin?

**Comment by bnagy** [comment]
I can just assume that if you don't provide a `@@` marker you want stdin, I think. Will look at it today.

**Comment by bnagy** [comment]
SO ANGRY RIGHT NOW

@yrp604 can you try with the `stdin` branch?

NOTE: If you set a memory limit for the fuzztarget that is lower than cwtriage needs itself then I think it will crash, so don't do that.

**Comment by yrp604** [comment]
Almost works.

``` diff
diff --git a/crashwalk.go b/crashwalk.go
index 914c88c..009efd4 100644
--- a/crashwalk.go
+++ b/crashwalk.go
@@ -222,9 +222,6 @@ func process(cw *Crashwalk, jobs <-chan Job, crashes chan<- crash.Crash, wg *syn
                        thisCmd = make([]string, len(cw.config.Command))
                        copy(thisCmd, cw.config.Command)
                }
-               if len(thisCmd) == 0 {
-                       log.Fatalf("internal error: Job command too short: %v\n", job)
-               }

                f, err := os.Open(job.Path)
                if err != nil {
```

Then I just had to modify francis to also have the filename param in Run() because go is strange and weird and I don't understand it. So maybe I didn't have to do that.

Then everything works. Thanks!

**Comment by bnagy** [comment]
OK, I switched back to the old ulimit and exec trick. It looks like gdb _does_ properly redirect its stdin to the inferior, so this is much cleaner. @yrp604 can you please test with branch `stdin2`?

I still don't see why you need that patch, btw, I tested -afl mode with a single command taking stdin and no args and didn't see the job too short error :| If you still have that problem I'll need more info to repro.

**Comment by yrp604** [comment]
Yeah, the new branch works. And I also can't repro the original issue i was having anymore either :| I assume I was screwing something up dumb last time, but that's weird.

Thanks again.

**Comment by bnagy** [comment]
merged this feature
