### ISSUE TITLE
feature request: support @@ inside argument string

### ISSUE THREAD

**Issue by kcwu** [bnagy/crashwalk#5]
Looks like cwtriage require @@ be a full string of one argument. But sometimes the filename is only part of argument string. For example,

```
$ cwtriage -root . -match crashes.\*id -- dd if=@@ of=/dev/null
2015/08/17 21:08:10 Unable to create Crashwalk: no substitute markers ( @@ ) in supplied command
```

"dd" is just an example

Could you also expand @@ inside argument string?
Thanks

**Comment by bnagy** [comment]
@kcwu I have implemented this in master, but I don't have an easy way to test it. Give it a spin and let me know if this is OK to close?

**Comment by bnagy** [comment]
OK, poke me if it still doesn't work for you. :)
