### ISSUE TITLE
-match doesnt exclude .cwtidy

### ISSUE THREAD

**Issue by yrp604** [bnagy/crashwalk#6]
This has a fun side effect! Every time you run it, it creates another .cwtidy directory in your cwtidy directory.

Example:

```
Command: xxx output/crashes/.cwtidy/.cwtidy/.cwtidy/yyy
File: output/crashes/.cwtidy/.cwtidy/.cwtidy/yyy
Error: no crash detected
```

**Comment by bnagy** [comment]
If you're doing -match yourself then my idea was that you should be doing -ignore (or negative matches in the match regex I guess).

I suppose it would be very unlikely to hurt to specify a default ignore for .cwtidy though

**Comment by bnagy** [comment]
@yrp604 give it a try now

**Comment by yrp604** [comment]
Fixed, thanks!
